Support Okta's response format
mbg/wai-saml2 pull request #12
Opened 2022-08-01 03:20 UTC by fumieval

The current version didn't work as-is because EncryptedKey is in a different location.

I changed the parser so that it accepts both KeyCloak's and Okta's responses, and added a test suite.

2022-08-17 00:55 UTC, fumieval commented
@mbg ping

2022-08-18 10:04 UTC, mbg requested changes
Hi @fumieval, thanks for opening this PR and sorry for the delay, I was travelling/on holiday. 

I have reviewed your proposed changes and there seems to be an issue with the parsing for `EncryptionMethod` which also causes the tests you have added to fail (thank you very much for adding those btw!). Can you have a look at that?

It might also be good to change the CI so that the tests are run there, but I am happy to make that change myself later after this PR is merged.

2022-08-18 10:04 UTC, mbg commented on package.yaml
> +    main: parser.hs
For consistency, it might be good to give the file a name starting with an upper-case character.

2022-08-18 10:04 UTC, mbg commented on src/Network/Wai/SAML2/XML/Encrypted.hs
> +            ]
There seems to be a breaking change here with respect to `algorithm` (although GitHub won't let me comment on that part, since it is unchanged). In the current version, `EncryptionMethod` is expected to be a child of `EncryptedData`, but in the proposed code it is now expected as a child of `EncryptedAssertion`.

Indeed, if I run the tests with `stack test`, both of them fail with an `Algorithm is required` error.

See https://www.samltool.com/generic_sso_res.php for some relevant examples.

2022-08-18 10:04 UTC, mbg commented on package.yaml
> +    language: Haskell2010
This appears to be an unrecognised field for `hpack`. I think it just generates the `default-language` field in the `.cabal` file anyway?

2022-08-19 01:38 UTC, fumieval commented on package.yaml
> +    language: Haskell2010
The latest version of hpack `0.35.0` says `default-language` is deprecated in favour of `language`

2022-08-19 01:42 UTC, fumieval commented on package.yaml
> +    main: parser.hs
I think lower-case file name is a common convention for main modules (cf. https://github.com/ekmett/lens/tree/master/tests). Rather, I intentionally use lower case to indicate that the module is not imported by anything else.

Renamed to Parser.hs anyway

2022-08-19 01:43 UTC, fumieval commented on src/Network/Wai/SAML2/XML/Encrypted.hs
> +            ]
Ah, it turns out that I dropped the crucial part of change while rebasing. It should be working now

2022-08-19 01:44 UTC, fumieval commented
I added a GitHub workflow step to run `stack test`

2022-08-23 13:13 UTC, mbg commented on package.yaml
> +    main: parser.hs
I can see that you have changed `parser` to `Parser` in the `package.yaml` file in https://github.com/mbg/wai-saml2/pull/12/commits/b067f098085755d5d0e5047ac384f53166cbf92b, but you haven't actually renamed the file itself, which seems to be the reason why the CI is currently failing.

2022-08-23 13:14 UTC, mbg commented on package.yaml
> +    language: Haskell2010
I saw that in the changes for `hpack`, but I couldn't get it to work with either `default-language` or `language`. I see you have removed that line in any case.

2022-08-23 13:18 UTC, mbg commented
@fumieval Thanks for adding the new step to the CI and making the other changes. 

In https://github.com/mbg/wai-saml2/pull/12/commits/9863e72d035b50c46255ba55a30889f202118dba, you remove a line for a case that is indeed currently redundant, but that is more a result of https://github.com/mbg/wai-saml2/blob/6d81ea83bd7a3c5ece0faee2db13d0be09ba8035/src/Network/Wai/SAML2/StatusCode.hs being incomplete, rather than the case actually being redundant. I would prefer if you drop https://github.com/mbg/wai-saml2/pull/12/commits/9863e72d035b50c46255ba55a30889f202118dba from this branch since it is unrelated to this PR and would have to be restored in the future.

2022-08-23 13:27 UTC, fumieval commented
OK, I was just wondering why CI is failing and suspected that the redundant case is the cause; removed that commit for now

2022-08-23 14:45 UTC, mbg commented
I commented on the CI failure [in the review conversation](https://github.com/mbg/wai-saml2/pull/12#discussion_r952611393). The file with the tests is still called `parser.hs`, even though you have updated `package.yaml` to refer to `Parser.hs`.

2022-08-24 00:49 UTC, fumieval commented on package.yaml
> +    main: parser.hs
Ah I see

2022-08-24 12:09 UTC, mbg approved these changes
Thanks, that seems to all work fine now! Thank you for contributing this!

2022-08-24 12:10 UTC, merged

2022-08-24 12:52 UTC, mbg commented
This is now released as https://hackage.haskell.org/package/wai-saml2-0.3.0.0, thank you again!

2022-08-24 12:58 UTC, fumieval commented
Great, thanks!